<?php
$host = '127.0.0.1';
$db = 'apotek_db';
$user = 'root';
$pass = '';
$charset = 'utf8mb4';

$dsn = "mysql:host=$host;dbname=$db;charset=$charset";
$opt = [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    PDO::ATTR_EMULATE_PREPARES => false,
];

try {
    $pdo = new PDO($dsn, $user, $pass, $opt);
    echo "Connected successfully to $db\n";
} catch (\PDOException $e) {
    die("Connection failed: " . $e->getMessage());
}

$tables = [];
$stmt = $pdo->query("SHOW TABLES");
while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
    $tables[] = $row[0];
}

$outputFile = __DIR__ . '/database.sql';
$handle = fopen($outputFile, 'w+');

if (!$handle) {
    die("Cannot open file:  $outputFile");
}

fwrite($handle, "-- Database: $db\n");
fwrite($handle, "-- Generated by Agentic AI\n\n");
fwrite($handle, "SET FOREIGN_KEY_CHECKS=0;\n");

foreach ($tables as $table) {
    echo "Exporting table: $table\n";
    $row = $pdo->query("SHOW CREATE TABLE `$table`")->fetch(PDO::FETCH_NUM);
    fwrite($handle, "\n\n-- Table structure for table `$table`\n");
    fwrite($handle, "DROP TABLE IF EXISTS `$table`;\n");
    fwrite($handle, $row[1] . ";\n\n");

    fwrite($handle, "-- Dumping data for table `$table`\n");
    $rowCount = 0;

    // Use unbuffered query for large tables
    $pdo->setAttribute(PDO::MYSQL_ATTR_USE_BUFFERED_QUERY, false);
    $rows = $pdo->query("SELECT * FROM `$table`");

    while ($r = $rows->fetch(PDO::FETCH_ASSOC)) {
        $values = [];
        foreach ($r as $v) {
            if ($v === null)
                $values[] = "NULL";
            else
                $values[] = $pdo->quote($v);
        }
        $line = "INSERT INTO `$table` VALUES (" . implode(', ', $values) . ");\n";
        fwrite($handle, $line);
        $rowCount++;
    }
    $pdo->setAttribute(PDO::MYSQL_ATTR_USE_BUFFERED_QUERY, true);
    echo "  Rows: $rowCount\n";
}

fwrite($handle, "\nSET FOREIGN_KEY_CHECKS=1;\n");
fclose($handle);
echo "Database dump created at: $outputFile\n";
